[project]
name = "ostadsgo-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "markdown>=3.8",
    "pygments>=2.19.1",
]
